// action type 常量
const SEARCH_FOCUS = 'header/SEARCH_FOCUS'
const SEARCH_BLUR = 'header/SEARCH_BLUR'
const SEARCH_TRENDING = 'header/SEARCH_TRENDING'
const MOUSE_ENTER = 'header/MOUSE_ENTER'
const MOUSE_LEAVE = 'header/MOUSE_LEAVE'
const CHANGE_PAGE = 'header/CHANGE_PAGE'

export { SEARCH_FOCUS, SEARCH_BLUR, SEARCH_TRENDING, MOUSE_ENTER, MOUSE_LEAVE, CHANGE_PAGE }
