// action type 常量
const SEARCH_FOCUS = 'header/SEARCH_FOCUS'
const SEARCH_BLUR = 'header/SEARCH_BLUR'
const SEARCH_TRENDING = 'header/SEARCH_TRENDING'

export { SEARCH_FOCUS, SEARCH_BLUR, SEARCH_TRENDING }
