const CHANGE_HOME_DATA = 'home/CHANGE_HOME_DATA'
const GET_MORE_ARTICLE_LIST = 'home/GET_MORE_ARTICLE_LIST'
const LOADING_STATE = 'home/LOADING_STATE'

export { CHANGE_HOME_DATA, GET_MORE_ARTICLE_LIST, LOADING_STATE }
